### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by YChaeeun** [Nexters/Sticky-Android#6]
### TODO
- UI
  - [x] xml 레이아웃 작성
  - [x] 리사이클러뷰
  - [x] 타이머
  - [x] 다이얼로그
  - [ ] 디자인 가이드 적용
- GPS
  - [ ] 권한
  - [ ] 백그라운드 동작 처리
  - [ ] 집 안/밖 판단 로직
 - Room 
   - [ ] gps 정보 처리
   - [ ] 뱃지&레벨 정보 처리
  - 동작 플로우 정리
